# Generated by Django 3.0.4 on 2020-04-26 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelist',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
